from langchain_core.prompts import PromptTemplate


SEARCH_QUERY_GENERATOR_PROMPT = PromptTemplate.from_template(template="""
You are a query generation agent for academic research.

Given a search intent and past queries (generated by you), your job is to generate a diverse set of precise search queries suitable for retrieving relevant papers from arXiv to try to gather context about the search intent.

Instructions:

1. Break down the user query into key concepts, methods, domains, authors, and subfields.

2. Generate minimum of 2 and maximum of 4 search queries that:

   * Use technical and domain-specific language
   * Cover different angles of the problem (methods, applications, theory, synonyms)
   * Include variations in phrasing and terminology

3. Avoid redundancy — each query should retrieve different types of papers.
   Do not reuse wording from past queries unless necessary; prefer unexplored synonyms, adjacent methods, and neighboring subfields.

4. Prefer concise keyword-style queries rather than full sentences.

5. IMPORTANT: Each search query must be represented as a sequence of **atomic search terms** suitable for arXiv Advanced Search rows.

   * Each term entry must contain exactly ONE atomic concept, phrase, acronym, author name, or keyword
   * Do NOT place full boolean expressions inside a single term
   * Boolean logic must be expressed by using MULTIPLE term entries with row-level operators

   Correct:

   * AND `"gravitational waves"`
   * OR `GW`
   * OR `"event horizon"`

   Incorrect:

   * AND `("gravitational waves" OR GW OR "event horizon")`

6. Construct each atomic term using arXiv-compatible syntax wherever beneficial:

   * Use exact phrases in double quotes
   * Use acronyms and expanded forms as separate term entries
   * Use wildcards where useful
   * Use author formatting for researcher names
   * Include arXiv category identifiers when strongly implied
   * Preserve TeX expressions in `$...$`
   * Avoid parentheses unless absolutely necessary

7. Ensure diversity across precision and recall:

   * one broad exploratory query
   * one exact phrase / precision query
   * one method-focused query
   * one application/domain-focused query

8. Prefer field-aware terms:

   * exact phrases → title
   * methods / technical content → abstract
   * author names → author
   * broad exploration → all

9. Within each query:

   * use AND for major concept intersections
   * use OR for synonyms / acronyms
   * use NOT only when excluding clearly irrelevant interpretations

Output format:
{OUTPUT_FORMAT}

Search Intent:
{SEARCH_INTENTION}

Past Queries:
{PAST_QUERIES}
""")

COVERAGE_DECIDER_QUERY = PromptTemplate.from_template(template="""
You are a research coverage evaluator.

You are given:
- The original user query
- A set of research paper IDs and their abstracts

Your job is to determine based on their abstracts whether these articles collectively might provide sufficient coverage to answer the query.

Instructions:
1. Evaluate whether the selected articles, based on their abstracts:
   - Might cover the main aspects of the query
   - Might include relevant methods, evidence, or explanations
2. Identify missing aspects, if any:
   - Subtopics not covered
   - Important methods or perspectives missing
3. Decide:
   - If sufficient → stop
   - If insufficient → recommend the single most important thing to search and explore next, this will be used as a search intention by the agent.

Output format:
{OUTPUT_FORMAT}
                                                      
User Query:
{QUERY}
                                                      
Articles:
{ARTICLES}
""")
