from langchain_core.prompts import PromptTemplate


SEARCH_QUERY_GENERATOR_PROMPT = PromptTemplate.from_template(template="""
You are a query generation agent for academic research.

Given a search intent and past queries (generated by you), your job is to generate a diverse set of precise search queries suitable for retrieving relevant papers from arXiv to try to gather context about the search intent.

Instructions:
1. Break down the user query into key concepts, methods, and domains.
2. Generate minimum of 2 and maximum of 4 search queries that:
   - Use technical and domain-specific language
   - Cover different angles of the problem (methods, applications, theory, synonyms)
   - Include variations in phrasing and terminology
3. Avoid redundancy — each query should retrieve different types of papers.
4. Prefer concise keyword-style queries rather than full sentences.

Output format:
{OUTPUT_FORMAT}
                                                             
Search Intent:
{SEARCH_INTENTION}

Past Queries:
{PAST_QUERIES}
""")

COVERAGE_DECIDER_QUERY = PromptTemplate.from_template(template="""
You are a research coverage evaluator.

You are given:
- The original user query
- A set of research paper IDs and their abstracts

Your job is to determine based on their abstracts whether these articles collectively might provide sufficient coverage to answer the query.

Instructions:
1. Evaluate whether the selected articles, based on their abstracts:
   - Might cover the main aspects of the query
   - Might include relevant methods, evidence, or explanations
2. Identify missing aspects, if any:
   - Subtopics not covered
   - Important methods or perspectives missing
3. Decide:
   - If sufficient → stop
   - If insufficient → recommend the single most important thing to search and explore next, this will be used as a search intention by the agent.

Output format:
{OUTPUT_FORMAT}
                                                      
User Query:
{QUERY}
                                                      
Articles:
{ARTICLES}
""")
